### ISSUE TITLE
Grouping plugins by author

### ISSUE THREAD

**Issue by draylegend** [PenguLoader/PenguLoader#100]
## The idea

is to let devs create a folder that represents their `username` or similar unique ID. Inside that folder they can put their plugins.

### Current project structure:

```
plugins/
  best-plugin-ever.js
  plugin-name-1.js
  plugin-name-2/
    index.js
config
core.dll
datastore
"Pengu Loader.exe"
```

### I think there're some devs who'd like to have the following structure

```
plugins/
  best-plugin-ever.js
  some-author/ <- Group by author
    plugin-name-1.js
    plugin-name-2/
      index.js
config
core.dll
datastore
"Pengu Loader.exe"
```

Extra folder inside plugins allows to group plugins from the same author.

**Comment by nomi-san** [comment]
Will add support this feature for plugin folder names start with **@**.
Like, a npm package name thats scoped by its own organization.
Also the top-level `index.js` inside this `@org` will be ignored.

For example group plugins by BakaFT

```
plugins/
  |__@BakaFT
  . |__plugin-1/
    . |__index.js
    |__plugin-2/
    . |__index.js
    
-> @BakaFT/plugin-1
-> @BakaFT/plugin-2
```
