### ISSUE TITLE
Plugin Browser

### ISSUE THREAD

**Issue by Elektroney** [PenguLoader/PenguLoader#104]
I dont know if this is a smart idea to implement due to the projects size so just putting this out here due to how easy it would be to implement

**Comment by BakaFT** [comment]
What exactly is **Plugin Browser**?

**Comment by Elektroney** [comment]
A potential section in the programm that would show you all available plugins and you can install them by just clicking on them

**Comment by BakaFT** [comment]
Oh this is usually called Plugin Store in Pengu DC server.

This is on roadmap now, and may or may not release with new Loader GUI.
