### ISSUE TITLE
erro microsoft

### ISSUE THREAD

**Issue by mihawk6lol** [PenguLoader/PenguLoader#105]
![imagem_2024-01-01_172026426](https://github.com/PenguLoader/PenguLoader/assets/155392609/384af040-14d2-45de-bf9c-ecd521a109be)

**Comment by nomi-san** [comment]
Duplicate #74, #64, #63

**Comment by nomi-san** [comment]
There's a solution.

1. Download this [dev build](https://github.com/PenguLoader/PenguLoader/actions/runs/7372101947) in Actions:

![image](https://github.com/PenguLoader/PenguLoader/assets/38210249/e1df7cb6-4fd3-4e15-8286-f49335ea9092)

2. Open app once and close it.
3. Add this line to the `config` file:

```
UseSymlink=1
```

4. Open app again, select League path, then press **Activate** as normal.
