### ISSUE TITLE
能否增加一个拦截直播弹窗？

### ISSUE THREAD

**Issue by Qcby** [PenguLoader/PenguLoader#114]
![image](https://github.com/PenguLoader/PenguLoader/assets/35736643/2123f1e8-5fef-4c9d-a6af-2ede20a63895)
能否增加一个拦截直播弹窗，登录就自动弹出来。我不看直播不需要。所以能不能支持把它干掉！

**Comment by BakaFT** [comment]
Pengu Loader 是一个通用性质的 JavasScript 插件加载器，请不要在这里提 Issue 询问这些需求。

然而 Discord 社区的大部分成员都是世界各地的直营服玩家，所以你在 DC服务器也大概率得不到帮助。

很抱歉，我需要关闭你的 Issue， 因为你提出了基本不会有解决方案的问题。
