### ISSUE TITLE
custom scheme

### ISSUE THREAD

**Issue by VanillaMaster** [PenguLoader/PenguLoader#118]
why use fake domain when it can be custome url scheme (is it even possible)?

**Comment by nomi-san** [comment]
LCU responds with header `Referrer Policy: strict-origin-when-cross-origin`.
Then all cross-orgin and cross-scheme (`https` -> `pengu://`) requests will be blocked.
Since Chromium v87, there's no way to bypass CORS policy, disabling whole web security is not a good idea.

**Comment by VanillaMaster** [comment]
@nomi-san as far as i can see, it manageable

[  virtual bool AddCustomScheme(const CefString& scheme_name, int options) = 0;](https://github.com/chromiumembedded/cef/blob/54a9c26b92271ca060793ed3de5348bb0f42c06c/include/cef_scheme.h#L96)

[ CEF_SCHEME_OPTION_CORS_ENABLED = 1 << 4 ](https://github.com/chromiumembedded/cef/blob/54a9c26b92271ca060793ed3de5348bb0f42c06c/include/internal/cef_types.h#L3193)

**Comment by nomi-san** [comment]
Yesh, this method allows cross-scheme `import`, but cant bypass resource requests.
Also tried `CefAddCrossOriginWhitelistEntry()`.

```cpp
// This function cannot be used to bypass the restrictions on local or display
// isolated schemes. See the comments on CefRegisterCustomScheme for more
// information.
```

**Comment by VanillaMaster** [comment]
@nomi-san it can, i playing around and now at the point where i just not good enough to implement `cef_resource_handler_t` and i just get crashes, but request doesnt get blocked by cors

**Comment by nomi-san** [comment]
Fetch API should not work on non HTTP scheme, even with `CEF_SCHEME_OPTION_CORS_ENABLED`.

**Comment by VanillaMaster** [comment]
but esm imports works fine

**Comment by VanillaMaster** [comment]
> Fetch API should not work on non HTTP scheme, even with `CEF_SCHEME_OPTION_FETCH_ENABLED`.

then whats the point of thet option ...

**Comment by nomi-san** [comment]
In case of switching to custom scheme, what will you do
- Replacing `https://plugins` with `pengu://plugins`, that has no meaning
- Replacing `https://plugins` with `plugins://<name>` (name is TLD, alias of pkg), you will do more work

And both cases need to redirect ALL requests that point to `https://plugins/`. Also exising plugins have used fetch to acquire their resouces will not work.

I will not handle this case.
