### ISSUE TITLE
Your League Client is not supported or your Pengu version is out of date

### ISSUE THREAD

**Issue by 1019088775** [PenguLoader/PenguLoader#127]
14.17.609.2293
![11](https://github.com/user-attachments/assets/7e94a825-a3c8-4125-b85f-bbdc87ff5e0a)

**Comment by BakaFT** [comment]
This screenshot should be from PBE

According to the code, they might upgraded the CEF, I will check on this
https://github.com/PenguLoader/PenguLoader/blob/a18a1f049438f92e4aafbff8bdfe6ba6bd97b99a/core/src/libcef.cc#L36

**Comment by BakaFT** [comment]
![image](https://github.com/user-attachments/assets/e466b9c5-2458-41d6-bafd-debd6127adda)

Yes. PBE is on Chromium 108 now while Live is still on 91, please wait for update.

Usually this only happen like every several years, so PL is not ready for this situation that live and pbe are in different version.

**Comment by BakaFT** [comment]
https://github.com/BakaFT/PenguLoader/tree/feat/cef108

clone this branch if anyone is willing to compile themselves
![image](https://github.com/user-attachments/assets/6842ce60-167c-4cba-9945-4db8eff5a4a9)

**Comment by nomi-san** [comment]
@Lrony try it: https://github.com/PenguLoader/PenguLoader/actions/runs/10382690577

![image](https://github.com/user-attachments/assets/793ce38d-cdfb-4a5b-a09d-c33dc4ac5b78)

You also need to add new `config` to open devtools:

```ini
[client]
use_devtools = true
```

**Comment by nomi-san** [comment]
Fixed in the latest release.
