### ISSUE TITLE
How to run PenguLoader

### ISSUE THREAD

**Issue by Duga123vn4** [PenguLoader/PenguLoader#46]
## Where i can find PenguLoader.exe to run it ?

![s](https://user-images.githubusercontent.com/90487552/226081476-fdb22823-a523-410c-8ad6-f0f1619a2e5d.png)

**Comment by nomi-san** [comment]
The loader is not released yet, you should download the auto-build version from Actions, then pick the newest runner to download it.

https://github.com/PenguLoader/PenguLoader/actions

![image](https://user-images.githubusercontent.com/38210249/226081743-a9cc8bb2-8fb8-49d3-904c-3c45f7c401e9.png)
