### ISSUE TITLE
failed to perform activation

### ISSUE THREAD

**Issue by goohjgf** [PenguLoader/PenguLoader#63]
Hello,i have issue. When i turn  "Active status" to On i have error: failed to perform activation
![Снимок экрана (1828)](https://github.com/PenguLoader/PenguLoader/assets/122902925/3e43b446-561b-401c-9d3d-5f4643796d11)

**Comment by Elaina69** [comment]
> Hello,i have issue. When i turn "Active status" to On i have error: failed to perform activation ![Снимок экрана (1828)](https://user-images.githubusercontent.com/122902925/248171071-3e43b446-561b-401c-9d3d-5f4643796d11.png)

make sure you disable windows defender or let pengu inside excluse list before install, open and active

**Comment by goohjgf** [comment]
I have diasbled windows defender

**Comment by nomi-san** [comment]
Reinstall without denfender or add PL to exclusion.

English message:
> "Attempted to perform an unauthorized operation"

If you get this error again, make sure PL is run as admin.
Commonly, this error is raised when your windows account is a standard user or no permission to modify local machine registry. Please upgrade your windows account to administrator.
