### ISSUE TITLE
Failed to perform activation 

### ISSUE THREAD

**Issue by Wridell** [PenguLoader/PenguLoader#64]
При установке/распаковке программы появляется одна и та же ошибка, не даёт активировать программу и собственно воспользоваться ей. прошу пояснить как её исправить, защитник виндовс отключен, антивирус тем более, удалял и переустанавливал программу на несколько разных дисков, в названии папки только латиница , вот. 
![Screenshot_4](https://github.com/PenguLoader/PenguLoader/assets/137519310/02daed9f-3a6b-4ea5-ab56-b65f0c6691aa)
Устанавливал на отдельный жесткий диск, и на жеёсткий диск где находится лига.

**Comment by nomi-san** [comment]
Duplicate #63 😉
