### ISSUE TITLE
Feature: a fallback injection method using symlink

### ISSUE THREAD

**Issue by BakaFT** [PenguLoader/PenguLoader#77]
We got so many reports that user can not write IFEO registry keys due to an `Unauthorized Exception`. e.g: #74  #63  #64. This may be caused by many reasons(Anti-virus, no admin privilege...etc), so we need to find a fallback method just in case of it. 

Luckily we still have the Dll Proxing way working(by creating a symlink named `d3d9.dll/dinput.dll/dwrite.dll` pointing to `core.dll` besides `LeagueClient.exe` . But the problem is we need to make a GUI to do this thing to make it user-friendly.

- [x] Implement GUI for symlink (windows only now)
- ~~Mutliple LeagueClient support~~

**Comment by nomi-san** [comment]
Adding multi-client support is not necessary at this point, because almost these users just use one client.
