### ISSUE TITLE
Simple Optimization

### ISSUE THREAD

**Issue by fkue587** [PenguLoader/PenguLoader#88]
Can't edit heroes in advance
Need a config file to edit advance hero replacement
It is not convenient to use the mouse wheel to select heroes to find them

**Comment by BakaFT** [comment]
你直接用中文说。。我看不懂你说的话。

**Comment by valhir** [comment]
秒选器插件问题建议请移步[https://github.com/controlado/auto-champion-select](url)
不要在pl这里提

**Comment by BakaFT** [comment]
i guess this should be an auto pick/ban plugin issue. 

he must mixed up the concept of loader amd plugin.

and i will close this issue for it's not related.
