### ISSUE TITLE
DevTools display on 2k screen

### ISSUE THREAD

**Issue by nitznic** [PenguLoader/PenguLoader#91]
The font size of devtools displayed on the 2k screen is too small，What should I do?
![devtools](https://github.com/PenguLoader/PenguLoader/assets/53138093/cd69595b-a0cd-4f66-b5c8-1f3be73c5d7c)

**Comment by BakaFT** [comment]
Try to zoom it with `Ctrl`+`Shift`+`+`

**Comment by nomi-san** [comment]
We should set zoom level by default before showing the DevTools window.

1. Get window's `DPI`
2. Calculate zoom level by `DPI / 96.0`
3. Call `CefBrowserHost::SetZoomLevel()`

**Comment by nitznic** [comment]
> Try to zoom it with `Ctrl`+`Shift`+`+`

it's worked,thx
